// src/components/StatBars.vue
<template>
  <section>
    <figure class="bar" v-for="(stat, index) in statSet" :key="index">
      <div>
        <span :style="{ height: `${(100 * stat.current) / stat.max}%` }"></span>
      </div>
    </figure>
  </section>
</template>

<script lang="ts">
import { Options, Vue } from "vue-class-component";
import gameStore from "@/store";
import { Character } from "@/rpg-classes/Character";
import { PointBar } from "@/rpg-classes/CharacterStats";

@Options({
  components: {},
  props: {
    character: Character,
  },
})
export default class StatBars extends Vue {
  $store!: typeof gameStore;
  character!: Character;

  get health(): PointBar {
    return this.statSet[0];
  }
  get stamina(): PointBar {
    return this.statSet[1];
  }
  get mana(): PointBar {
    return this.statSet[2];
  }

  get statSet(): PointBar[] {
    this.$store.getters.timestamp;
    const { health, stamina, mana } = this.character.data.stats;
    return [health, stamina, mana];
  }
}
</script>

<style scoped lang="scss">
section {
  display: flex;
  justify-content: space-around;
  width: 4rem;
}

.bar {
  margin: 0;

  div {
    position: relative;
    width: 0.5rem;
    height: 3rem;
    background-color: white;
    box-sizing: border-box;
    padding: 0;
  }
  span {
    position: absolute;
    box-sizing: border-box;
    bottom: 0;
    left: 0;
    width: 100%;
    background-color: black;
    padding: 0;
    margin: 0;
  }
}
</style>

// two-point-five/src/components/StatBars.tsx
import { CharacterStats, PointBar } from "@/rpg-classes/CharacterStats";

interface Props {
    stats: CharacterStats
}

const Bar = ({ stat }: { stat: PointBar }) =>
    <div style={{ position: 'relative', height: 75, width: 10 }}>
        <progress
            style={{
                width: 75,
                height: 15,
                display: 'block',
                transformOrigin: 'top left',
                transform: 'translateY(100%) rotate(-90deg) translateY(-16%)',
                position: 'absolute',
                bottom: 0,
                left: 0,
            }}
            max={stat.max} value={stat.current}
        />
    </div>

export const StatBars = ({ stats }: Props) => {

    return <div style={{ display: 'inline-flex', width:30 }}>
        <Bar stat={stats.health} />
        <Bar stat={stats.stamina} />
        <Bar stat={stats.mana} />
    </div>
}
